TEST DO NOT LAND LOOKING AT PORTS
aptos-labs/aptos-ts-sdk pull request #42
Opened 2023-10-13 17:51 UTC by banool

### Description

### Test Plan

### Related Links

2023-10-14 03:06 UTC, gregnazario requested changes
Not letting you land it :)

2023-10-16 01:36 UTC, 0xmaayan commented
> 2. The user txn processor currently breaks when handling txns with secp256. This is the case across all networks and in main, so it's just totally broken upstream. This PR skips those tests for now to make CI green.


thats weird.... I was able to run secp256k1 tests separately

2023-10-16 03:32 UTC, banool commented
Idk Larry says it's meant to be broken on both? I'll look into it, maybe he landed a fix.

2023-10-16 16:38 UTC, gregnazario approved these changes

2023-10-16 17:48 UTC, 0xmaayan approved these changes

2023-10-16 17:56 UTC, merged