bug: Fix fundAccount always waiting for Indexer
aptos-labs/aptos-ts-sdk pull request #442
Opened 2024-06-20 20:50 UTC by jmintuitive

### Description

Funding an account using the faucet currently always triggers waits for the indexer since `undefined !== false` is `true`.
<img width="957" alt="image" src="https://github.com/aptos-labs/aptos-ts-sdk/assets/163934542/ec1f397d-5974-4502-a53e-a71217ddc4b3">
This PR updates the logic so that it only waits for the indexer if `options.waitForIndexer` is `true`. 

This was found by trying to run `simple_transfer.ts` in the example folder, and immediately getting this error: 
```
 [AptosApiError]: Indexer error: field 'processor_status' not found in type: 'query_root'
    at Gn (/Users/jacksonmills/aptos-ts-sdk/dist/common/index.js:1:36526)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async f (/Users/jacksonmills/aptos-ts-sdk/dist/common/index.js:470:383)
    at async tc (/Users/jacksonmills/aptos-ts-sdk/dist/common/index.js:470:571)
    at async Hn (/Users/jacksonmills/aptos-ts-sdk/dist/common/index.js:470:694)
    at async Zn (/Users/jacksonmills/aptos-ts-sdk/dist/common/index.js:470:12500)
    at async gn.fundAccount (/Users/jacksonmills/aptos-ts-sdk/dist/common/index.js:470:55884)
    at async example (/Users/jacksonmills/aptos-ts-sdk/examples/typescript/simple_transfer.ts:57:24) {
  url: 'https://api.devnet.aptoslabs.com/v1/graphql',
  status: 200,
  statusText: 'OK',
  data: { errors: [ [Object] ] },
  request: {
    url: 'https://api.devnet.aptoslabs.com/v1/graphql',
    method: 'POST',
    originMethod: 'getProcessorStatuses',
    path: '',
    body: {
      query: '\n' +
        '    query getProcessorStatus($where_condition: processor_status_bool_exp) {\n' +
        '  processor_status(where: $where_condition) {\n' +
        '    last_success_version\n' +
        '    processor\n' +
        '    last_updated\n' +
        '  }\n' +
        '}\n' +
        '    '
    },
    contentType: undefined,
    acceptType: undefined,
    params: undefined,
    overrides: { WITH_CREDENTIALS: false, HEADERS: {} }
  }
}
```

While this fix solves the immediate issue for the tutorial, it does NOT address why `processor_status` was not found in the `query_root` for the devnet indexer. **That should be investigated separately.**

(I also updated the contributing guide to clearly spell out how to test code since it was very easy to miss when skimming.)

### Test Plan

BEFORE:
![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/62d38a68-3346-4b9c-8f28-875b5afe6215/ca37ba26-900f-4299-966a-307ecc0a5605/Untitled.png)

AFTER:
<img width="957" alt="image" src="https://github.com/aptos-labs/aptos-ts-sdk/assets/163934542/7717db6b-c638-4d93-a37c-eb9b8b2d85eb">

### Related Links

2024-06-20 20:55 UTC, gregnazario approved these changes

2024-06-20 20:57 UTC, 0xmaayan commented on CONTRIBUTING.md
> +4. Ensure all tests and lints pass on each and every commit that is part of your pull request using `pnpm test && pnpm lint`.
make sure to update CHANGELOG =)

2024-06-21 06:20 UTC, banool approved these changes

2024-06-21 19:30 UTC, 0xmaayan commented
ok, so tests are failing because of this change.

2024-07-02 21:26 UTC, gregnazario commented
> ok, so tests are failing because of this change.

We'll need to probably set the field for a lot of tests

2024-07-10 23:43 UTC, 0xmaayan requested changes
we should not change the default fundAccount behavior and keep it to always wait for indexer. lets revert this change and keep all the other stuff

2024-07-12 18:42 UTC, jmintuitive commented
@0xmaayan Updated the logic so it's more explicit that `undefined` means that we wait for the indexer (this is functionally equivalent to the old default of always waiting :) )

This is ready for re-review when you have a chance :)

2024-07-12 18:52 UTC, 0xmaayan commented on examples/typescript/your_fungible_asset.ts
> +    options: { waitForIndexer: true },
dont need it

2024-07-12 18:52 UTC, 0xmaayan commented on examples/typescript/your_coin.ts
> +    options: { waitForIndexer: true },
dont need it

2024-07-12 18:52 UTC, 0xmaayan commented on examples/typescript/simple_sponsored_transaction.ts
> +    options: { waitForIndexer: true },
dont need it

2024-07-12 18:52 UTC, 0xmaayan commented on examples/javascript/simple_sponsored_transaction.js
> +    options: { waitForIndexer: true },
dont need it

2024-07-12 19:03 UTC, jmintuitive commented
@0xmaayan Updated to remove the unnecessary `option: { waitForIndexer = true }` lines :)

2024-07-12 19:05 UTC, 0xmaayan approved these changes
LGTM. please update CHANGELOG with the check changes in fundAccount

2024-07-17 21:12 UTC, merged